### ISSUE TITLE
Add officially supported ways of pulling in extra js and css files for plugins

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1114]
Right now you have to hack it in some way or another, which is subject to breaking. The first thought that came to mind would be something in plugin.yml's grunt object:

```
grunt:
    prependJsFiles:
        - bower_components/foo/foo.js
        - node_modules/bar/bar.js
    appendCssFiles:
        - bower_components/foo/foo.css
```

There would be both prepend and append options for JS and CSS files to be built into plugin.min.js and plugin.min.css, and the paths would be relative to the plugin root directory.

A second option would be to expose some functions that could be called inside plugin Gruntfiles at config time.

ping @jbeezley
