### ISSUE TITLE
girder ansible module: making public collection doesn't seem to work

### ISSUE THREAD

**Issue by zachmullen** [girder/girder#1486]
The following doesn't work:

```
girder:
    username: "{{ girder_admin_user }}"
    password: "{{ girder_admin_password }}"
    port: "{{ girder_socket_port }}"
    collection:
      name: TCGA
      public: true
    state: present
```

The collection is created as private. I also tried `public: yes`, but no luck that way either.

@kotfic is this an easy fix?
