### ISSUE TITLE
Create global connection variables in Girder ansible module

### ISSUE THREAD

**Issue by danlamanna** [girder/girder#2052]
We should define variables such as `girder_client_username` and `girder_client_password` and so on so code similar to this:
```
tasks:
  - name: Create filesystem assetstore
    girder:
      port: 8080
      username: "admin"
      password: "letmein"
      assetstore:
        name: "Temp Filesystem Assetstore"
        type: "filesystem"
        root: "/tmp/"
        current: true
      state: present
        
  - name: Create collection for folder
    girder:
      port: 8080
      username: "admin"
      password: "letmein"
      collection:
        name: "Test Collection"
        description: "A test collection"
    register: test_collection    
```

Can be rewritten as this:
```
vars:
  girder_client_username: "admin"
  girder_client_password: "letmein"
  girder_client_port: 8080

tasks:
  - name: Create filesystem assetstore
    girder:
      assetstore:
        name: "Temp Filesystem Assetstore"
        type: "filesystem"
        root: "/tmp/"
        current: true
      state: present

  - name: Create collection for folder
    girder:
      collection:
        name: "Test Collection"
        description: "A test collection"
    register: test_collection
```
