### ISSUE TITLE
Add mention of WSGI + GIL caveats, especially for Elastic Beanstalk

### ISSUE THREAD

**Issue by EricCousineau-TRI** [girder/girder#2611]
@jamiesnape found that we were getting crashes from Girder on a deployed Beanstalk instance due to WSGI and GIL shenanigans indicated here:
http://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html#python-simplified-gil-state-api

He followed these instructions and we have been getting fewer failures on Beanstalk - there are still some, but we are trying to figure out what their root cause is.

It'd be nice if this were mentioned in the documentation - I do not see it mentioned under the **WSGI** or **Beanstalk** sections in the **Deploy** docs:
http://girder.readthedocs.io/en/latest/deploy.html#elastic-beanstalk

**Comment by danlamanna** [comment]
@EricCousineau-TRI Thanks for this Eric. I had expected there were areas within Girder which would violate some of the constraints of WSGI since our primary method of deployment is using CherryPy's HTTP server via a proxy pass, but I hadn't yet run into concrete issues.

@jamiesnape Could you detail the specific areas you've had problems with so far?

**Comment by jamiesnape** [comment]
A `/var/log/httpd/error_log` full of `Script timed out before returning headers: wsgi.py` initially. Those were reduced by changing `.ebextensions/wsgi.config` to
```
option_settings:
  aws:elasticbeanstalk:container:python:
    WSGIPath: "girder/wsgi.py"

files:
  "/etc/httpd/conf.d/wsgi_custom.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      WSGIApplicationGroup %{GLOBAL}
```
