### ISSUE TITLE
Autoreloader not starting in a development Docker 

### ISSUE THREAD

**Issue by Billuc** [girder/girder#3498]
Hi everyone !

I am working on a project using Girder, for which multiple custom plugins were developed.
I was tasked to dockerize this, girder and plugins included.
I handcrafted a dockerfile based on the girder/girder image. The main difference is that I have additional steps to install our custom plugins (pip installs). This container works great !

However, now, I want to create a dev container. This container should adapt its responses if the code of the plugins is modified. I installed the plugins with the '-e' options, used a volume to add the plugins' code in the container and created a new config file with server mode set to 'development'. 

In the logs I can see that the mode is now 'development', but when I modify the code of my plugins, I don't see those changes reflected in the responses (I tried with a test route returning True or False). I noticed that when running the girder/girder image I get a line telling me `Started monitor thread 'AutoReloader'`, and that I don't get it in my container's logs.

I guess this is linked to my problem, but I don't really see why I don't get this log.

Here is some code : 

**dev.dockerfile**

```
FROM node:14-bullseye as girder

WORKDIR /girder

# See http://click.pocoo.org/5/python3/#python-3-surrogate-handling for more detail on
# why this is necessary.
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY ./girder/scripts/setup.sh ./setup.sh
COPY ./girder/scripts/install_python.sh ./install_python.sh
RUN bash ./setup.sh
RUN bash ./install_python.sh
RUN rm ./setup.sh ./install_python.sh

RUN girder build --dev

EXPOSE 8080

CMD ["girder", "serve"]

FROM girder AS girder-plugins

COPY ./girder/scripts/install_plugins_dev.sh ./install_plugins_dev.sh
RUN chmod u+x ./install_plugins_dev.sh
RUN ./install_plugins_dev.sh
RUN girder build --dev

ARG GIRDER_CFG_FILE=./girder/girder.dist.cfg
COPY ${GIRDER_CFG_FILE} /girder/girder.cfg
ENV GIRDER_CONFIG /girder/girder.cfg
ENV WATCH_USEPOLLING true
```

**docker-compose.yml**

```
girder-dev:
    build:
      context: .
      dockerfile: ./girder/dev.dockerfile
      args:
        - GIRDER_CFG_FILE=./girder/girder.dev.cfg
    volumes:
      - ./girder/plugins:/girder/plugins
    networks:
      - mongodb_network
    profiles:
      - dev
```

For simplicity's sake I didn't include some bash files. You can consider that `install_plugins_dev.sh` runs `python3.8 -m pip install -e plugins/<PLUGIN_NAME>` for each of our custom plugins.
